language: "c"
install: "echo"

before_script:
     - sudo apt-get install libxenomai-dev
#    - sudo apt-get install gcc-avr binutils-avr avr-libc

script: "./configure --can=\"$CAN_DRIVER\" --timers=\"$TIMERS\" && make"
branches:
   only:
     - master
notifications:
  recipients:
    - hacking@taedcke.com
  email:
    on_success: change
    on_failure: always
  irc: "irc.freenode.org#canfestival"

env:
    - CAN_DRIVER="virtual"   TIMERS="unix"
    - CAN_DRIVER="vscom"     TIMERS="unix"
    - CAN_DRIVER="can4linux" TIMERS="unix"
    - CAN_DRIVER="lincan"    TIMERS="unix"
    - CAN_DRIVER="socket"    TIMERS="unix"
    - CAN_DRIVER="virtual"   TIMERS="xeno"
    - CAN_DRIVER="socket"    TIMERS="xeno"
